# Generated by Django 2.2.5 on 2019-12-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='作者姓名')),
                ('birthday', models.CharField(blank=True, max_length=100, null=True, verbose_name='出生年月')),
                ('author_description', models.TextField(blank=True, null=True, verbose_name='作者简介')),
                ('author_logo', models.TextField(blank=True, null=True, verbose_name='作者图片URL')),
            ],
            options={
                'verbose_name': '作者表',
                'verbose_name_plural': '作者表',
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '图书作者表',
                'verbose_name_plural': '图书作者表',
                'db_table': 'AuthorBook',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学院名称')),
                ('college_description', models.TextField(blank=True, null=True, verbose_name='学院简介')),
            ],
            options={
                'verbose_name': '学院表',
                'verbose_name_plural': '学院表',
                'db_table': 'College',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=100, verbose_name='图书名称')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社')),
                ('published', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版日期')),
                ('page', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='价格')),
                ('book_logo', models.TextField(blank=True, null=True, verbose_name='图书图片URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图书简介')),
                ('callnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='索书号')),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('authors', models.ManyToManyField(through='book.AuthorBook', to='book.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '图书表',
                'verbose_name_plural': '图书表',
                'db_table': 'Book',
            },
        ),
        migrations.AddField(
            model_name='authorbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='图书'),
        ),
        migrations.AddField(
            model_name='author',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.College', verbose_name='所属学院'),
        ),
    ]
