# Generated by Django 2.2.5 on 2019-12-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newpassword',
            field=models.CharField(default='', max_length=15, verbose_name='新密码'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
    ]
