# Generated by Django 2.2.5 on 2019-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191209_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='newpassword',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='新密码'),
        ),
    ]
